// Voice Agents Course Landing Content
export const SOURCE = 'voice-agents-course';
export const CAMPAIGN = { name: 'Voice Agents Course', startDate: '18 October 2024', startTime: '19:00', timezone: 'UTC+3', format: 'Live Group' };
export const HERO = { badge: '🔊 Live Course', title: 'Voice Agents: від ідеї до заробітків', subtitle: 'Навчись створювати надійних Voice-агентів, які заробляють гроші.', cta: 'Записатися на курс', note: 'Старт 18 жовтня. Місця обмежені!' };
export const SPEAKERS = [{ name: 'Сергій', role: 'AI-агент розробник', specialty: 'Voice Agents & Production' }, { name: 'Алекс', role: 'AI-агент розробник', specialty: 'Voice Agents & Production' }];
export const BENEFITS = [{ icon: '🔊', title: 'Voice-агенти з нуля', description: 'Розробляти агентів, які слухають і відповідають' }, { icon: '💰', title: 'Реальні заробітки', description: 'Як продавати Voice-агентів фрілансом' }, { icon: '🎯', title: 'Від хайпу до роботи', description: 'Бізнес платить за конкретні процеси' }];
export const AUDIENCES = { freelancers: { key: 'freelancers', buttonLabel: 'Фрілансер', formLabel: 'Я фрілансер', title: 'Фрілансерам: нова спеціалізація', description: 'Voice Agents — новий скіл на Upwork' }, digital: { key: 'digital', buttonLabel: 'Digital-спеціаліст', formLabel: 'Я digital-спеціаліст', title: 'Digital-фахівцям: нові можливості', description: 'Інтегруй Voice Agents у кампанії клієнтів' }, business: { key: 'business', buttonLabel: 'Бізнесмен / Інший', formLabel: 'Я бізнесмен', title: 'Всім: автоматизація голосом', description: 'Voice Agents скорочують час на обробку' } };
export const CURRICULUM = [{ day: 1, title: 'Voice Agents Basics', topics: ['Архітектура: ASR → LLM → TTS', 'Популярні інструменти', 'Де купляють Voice Agents'] }, { day: 2, title: 'Практика: будуємо агента', topics: ['Налаштування ASR', 'Логіка LLM', 'Синтез мови TTS', 'Live демо'] }, { day: 3, title: 'Від демо до заробітків', topics: ['Продажі на Upwork', 'Реальні кейси', 'Ціноутворення', 'Q&A'] }];
export const FOOTER = { text: 'MASC | Люди. Ідеї. AI-агенти.', tagline: 'Реальні навички для реальних задач.' };
